export class Users {
        static users = [
        {
            id: 1,
            name: "Mono Ranjan",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        {
            id: 2,
            name: "Mauro Sebastianelli",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        {
            id: 3,
            name: "Francesco Paternostro",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        {
            id: 4,
            name: "Shuja Hassan",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        {
            id: 5,
            name: "Leanne Graham",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        {
            id: 6,
            name: "Leanne Graham",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        {
            id: 7,
            name: "Leanne Graham",
            username: "Bret",
            email: "Sincere@april.biz",
            address: "tongi",
            street: "Kulas Light",
            suite: "Apt. 556",
            city: "Gwenborough",
            zipcode: "92998-3874",
        },
        ]
        
        static getAllUsers(){
            return this.users    // example with static data
        }   
}